name: Explorando-GitHub-Actions

on: [push, pull_request]

jobs:
  explorar:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1 - Mensaje de ejecución
        run: echo "El flujo de trabajo ha sido ejecutado en el evento: ${{ github.event_name }}"
        
      - name: Paso 2 - Información del repositorio
        run: echo "Tu repositorio es: ${{ github.repository }}"
        
      - name: Paso 3 - Mensaje de verificación
        run: echo "El flujo de trabajo está listo para verificar el código en el evento."
        
      - name: Paso 4 - Estado del trabajo
        run: echo "El estado del trabajo es: ${{ job.status }}."
